"""clean_sync_comparison

Revision ID: 0505300e6543
Revises: 6967d9f07f37
Create Date: 2026-03-18 14:34:15.857850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0505300e6543'
down_revision: Union[str, Sequence[str], None] = '6967d9f07f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviewsession', sa.Column('allow_question_navigate', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_column('user', 'profile_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('interviewsession', 'allow_question_navigate')
    # ### end Alembic commands ###
