"""remove team_id from papers

Revision ID: 0fe0fcfa0662
Revises: fc30b3cdf0c7
Create Date: 2026-03-12 13:54:49.196968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe0fcfa0662'
down_revision: Union[str, Sequence[str], None] = 'fc30b3cdf0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('codingquestionpaper_team_id_fkey'), 'codingquestionpaper', type_='foreignkey')
    op.drop_column('codingquestionpaper', 'team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codingquestionpaper', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('codingquestionpaper_team_id_fkey'), 'codingquestionpaper', 'team', ['team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
