"""add_max_sessions

Revision ID: 271e5c886c8d
Revises: 6f42d46ce0db
Create Date: 2026-01-22 09:57:28.985904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '271e5c886c8d'
down_revision: Union[str, Sequence[str], None] = '6f42d46ce0db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviewroom', sa.Column('max_sessions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviewroom', 'max_sessions')
    # ### end Alembic commands ###
