"""initial_schema

Revision ID: 399e1bb65c24
Revises: 
Create Date: 2026-02-16 15:27:17.228216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '399e1bb65c24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # helper to create type if not exists
    def create_enum_if_not_exists(enum_name, values):
        # PG specific: check if type exists before creating
        values_str = ", ".join(f"'{v}'" for v in values)
        bind.execute(sa.text(f"DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = '{enum_name}') THEN CREATE TYPE {enum_name} AS ENUM ({values_str}); END IF; END $$;"))

    try:
        create_enum_if_not_exists('userrole', ['ADMIN', 'SUPER_ADMIN', 'CANDIDATE'])
        create_enum_if_not_exists('interviewstatus', ['SCHEDULED', 'LIVE', 'COMPLETED', 'EXPIRED', 'CANCELLED'])
        create_enum_if_not_exists('candidatestatus', ['INVITED', 'LINK_ACCESSED', 'AUTHENTICATED', 'ENROLLMENT_STARTED', 'ENROLLMENT_COMPLETED', 'INTERVIEW_ACTIVE', 'INTERVIEW_PAUSED', 'INTERVIEW_COMPLETED', 'SUSPENDED'])
    except Exception as e:
        print(f"Enum creation skipped/failed (harmless if exists): {e}")

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SUPER_ADMIN', 'CANDIDATE', name='userrole'), nullable=False),
    sa.Column('resume_text', sa.String(), nullable=True),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('profile_image_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('face_embedding', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('questionpaper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionpaper_name'), 'questionpaper', ['name'], unique=False)
    op.create_table('interviewsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('schedule_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('max_questions', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'COMPLETED', 'EXPIRED', 'CANCELLED', name='interviewstatus'), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('current_status', sa.Enum('INVITED', 'LINK_ACCESSED', 'AUTHENTICATED', 'ENROLLMENT_STARTED', 'ENROLLMENT_COMPLETED', 'INTERVIEW_ACTIVE', 'INTERVIEW_PAUSED', 'INTERVIEW_COMPLETED', 'SUSPENDED', name='candidatestatus'), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('max_warnings', sa.Integer(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('suspension_reason', sa.String(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('enrollment_audio_path', sa.String(), nullable=True),
    sa.Column('candidate_name', sa.String(), nullable=True),
    sa.Column('admin_name', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['questionpaper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviewsession_access_token'), 'interviewsession', ['access_token'], unique=True)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('question_text', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('response_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['questionpaper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviewresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviewsession.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id')
    )
    op.create_table('proctoringevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('triggered_warning', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviewsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessionquestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviewsession.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statustimeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'LINK_ACCESSED', 'AUTHENTICATED', 'ENROLLMENT_STARTED', 'ENROLLMENT_COMPLETED', 'INTERVIEW_ACTIVE', 'INTERVIEW_PAUSED', 'INTERVIEW_COMPLETED', 'SUSPENDED', name='candidatestatus'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('context_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviewsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_result_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('candidate_answer', sa.String(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.Column('transcribed_text', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_result_id'], ['interviewresult.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('statustimeline')
    op.drop_table('sessionquestion')
    op.drop_table('proctoringevent')
    op.drop_table('interviewresult')
    op.drop_table('questions')
    op.drop_index(op.f('ix_interviewsession_access_token'), table_name='interviewsession')
    op.drop_table('interviewsession')
    op.drop_index(op.f('ix_questionpaper_name'), table_name='questionpaper')
    op.drop_table('questionpaper')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
