"""add invite_link to interviewsession

Revision ID: 5e1dbd0c8b43
Revises: 41958c02d377
Create Date: 2026-02-25 11:10:52.790986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e1dbd0c8b43'
down_revision: Union[str, Sequence[str], None] = '41958c02d377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interviewresponse')
    op.alter_column('answers', 'interview_result_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('interviewresult', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('proctoringevent', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sessionquestion', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('statustimeline', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.alter_column('statustimeline', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessionquestion', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('proctoringevent', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('interviewresult', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('answers', 'interview_result_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('interviewresponse',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('audio_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transcribed_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('similarity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('answer_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('evaluation_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('interview_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviewsession.id'], name=op.f('interviewresponse_interview_id_fkey')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('interviewresponse_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interviewresponse_pkey'))
    )
    # ### end Alembic commands ###
