"""add_admin_name_and_nullable_foreign_keys_for_hard_delete

Revision ID: 6f4451f41118
Revises: 4a8fe6c55e24
Create Date: 2026-02-12 10:30:53.837459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4451f41118'
down_revision: Union[str, Sequence[str], None] = '4a8fe6c55e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviewsession', sa.Column('admin_name', sa.String(), nullable=True))
    with op.batch_alter_table('interviewsession', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.alter_column('candidate_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)

    with op.batch_alter_table('questionpaper', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questionpaper', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('interviewsession', 'candidate_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('interviewsession', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('interviewsession', 'admin_name')
    # ### end Alembic commands ###
