"""add_binary_identity_storage

Revision ID: 7d16d933c5c5
Revises: 3a06be6b1e97
Create Date: 2026-02-04 09:06:15.296514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7d16d933c5c5'
down_revision: Union[str, Sequence[str], None] = '3a06be6b1e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image_bytes', sa.LargeBinary(), nullable=True))
    op.add_column('user', sa.Column('face_embedding', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'face_embedding')
    op.drop_column('user', 'profile_image_bytes')
    # ### end Alembic commands ###
