"""Add missing enum values for candidatestatus

Revision ID: 9a9a2845e9f9
Revises: c3d4e5f6a7b8
Create Date: 2026-02-27 13:43:51.683516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a9a2845e9f9'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agentsession_candidate_name'), table_name='agentsession')
    op.drop_table('agentsession')
    op.drop_index(op.f('ix_agentconversationturn_session_id'), table_name='agentconversationturn')
    op.drop_table('agentconversationturn')
    op.alter_column('answers', 'candidate_answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('answers', 'feedback',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('answers', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('answers', 'audio_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('answers', 'transcribed_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('answers_interview_result_id_fkey'), 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'interviewresult', ['interview_result_id'], ['id'], ondelete='CASCADE')
    op.alter_column('interviewresult', 'total_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('interviewresult_interview_id_fkey'), 'interviewresult', type_='foreignkey')
    op.create_foreign_key(None, 'interviewresult', 'interviewsession', ['interview_id'], ['id'], ondelete='CASCADE')
    op.alter_column('interviewsession', 'max_questions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('interviewsession', 'current_status',
               existing_type=postgresql.ENUM('INVITED', 'LINK_ACCESSED', 'AUTHENTICATED', 'ENROLLMENT_STARTED', 'ENROLLMENT_COMPLETED', 'INTERVIEW_ACTIVE', 'INTERVIEW_PAUSED', 'INTERVIEW_COMPLETED', 'SUSPENDED', name='candidatestatus'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.alter_column('interviewsession', 'last_activity',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('proctoringevent', 'details',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('proctoringevent_interview_id_fkey'), 'proctoringevent', type_='foreignkey')
    op.create_foreign_key(None, 'proctoringevent', 'interviewsession', ['interview_id'], ['id'], ondelete='CASCADE')
    op.alter_column('questionpaper', 'description',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('questionpaper', 'question_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('questionpaper', 'total_marks',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('questions', 'content',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('questions', 'question_text',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('questions', 'topic',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('sessionquestion_interview_id_fkey'), 'sessionquestion', type_='foreignkey')
    op.create_foreign_key(None, 'sessionquestion', 'interviewsession', ['interview_id'], ['id'], ondelete='CASCADE')
    op.alter_column('statustimeline', 'context_data',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('statustimeline_interview_id_fkey'), 'statustimeline', type_='foreignkey')
    op.create_foreign_key(None, 'statustimeline', 'interviewsession', ['interview_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statustimeline', type_='foreignkey')
    op.create_foreign_key(op.f('statustimeline_interview_id_fkey'), 'statustimeline', 'interviewsession', ['interview_id'], ['id'])
    op.alter_column('statustimeline', 'context_data',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'{}'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'sessionquestion', type_='foreignkey')
    op.create_foreign_key(op.f('sessionquestion_interview_id_fkey'), 'sessionquestion', 'interviewsession', ['interview_id'], ['id'])
    op.alter_column('questions', 'topic',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'General'::character varying"),
               existing_nullable=False)
    op.alter_column('questions', 'question_text',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'string'::character varying"),
               existing_nullable=False)
    op.alter_column('questions', 'content',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'string'::character varying"),
               existing_nullable=False)
    op.alter_column('questionpaper', 'total_marks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('questionpaper', 'question_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('questionpaper', 'description',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'proctoringevent', type_='foreignkey')
    op.create_foreign_key(op.f('proctoringevent_interview_id_fkey'), 'proctoringevent', 'interviewsession', ['interview_id'], ['id'])
    op.alter_column('proctoringevent', 'details',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.alter_column('interviewsession', 'last_activity',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('interviewsession', 'current_status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('INVITED', 'LINK_ACCESSED', 'AUTHENTICATED', 'ENROLLMENT_STARTED', 'ENROLLMENT_COMPLETED', 'INTERVIEW_ACTIVE', 'INTERVIEW_PAUSED', 'INTERVIEW_COMPLETED', 'SUSPENDED', name='candidatestatus'),
               nullable=True)
    op.alter_column('interviewsession', 'max_questions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'interviewresult', type_='foreignkey')
    op.create_foreign_key(op.f('interviewresult_interview_id_fkey'), 'interviewresult', 'interviewsession', ['interview_id'], ['id'])
    op.alter_column('interviewresult', 'total_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key(op.f('answers_interview_result_id_fkey'), 'answers', 'interviewresult', ['interview_result_id'], ['id'])
    op.alter_column('answers', 'transcribed_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('answers', 'audio_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('answers', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('answers', 'feedback',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('answers', 'candidate_answer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('agentconversationturn',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('turn_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('speaker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agentsession.id'], name=op.f('agentconversationturn_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agentconversationturn_pkey'))
    )
    op.create_index(op.f('ix_agentconversationturn_session_id'), 'agentconversationturn', ['session_id'], unique=False)
    op.create_table('agentsession',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('agentsession_pkey'))
    )
    op.create_index(op.f('ix_agentsession_candidate_name'), 'agentsession', ['candidate_name'], unique=False)
    # ### end Alembic commands ###
