"""add_candidate_status_tracking_system

Revision ID: a961e08d049d
Revises: eb51f9bae24a
Create Date: 2026-02-09 16:26:28.275806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a961e08d049d'
down_revision: Union[str, Sequence[str], None] = 'eb51f9bae24a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statustimeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'LINK_ACCESSED', 'AUTHENTICATED', 'ENROLLMENT_STARTED', 'ENROLLMENT_COMPLETED', 'INTERVIEW_ACTIVE', 'INTERVIEW_PAUSED', 'INTERVIEW_COMPLETED', 'SUSPENDED', name='candidatestatus'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('context_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interviewsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('interviewsession', sa.Column('current_status', sa.Enum('INVITED', 'LINK_ACCESSED', 'AUTHENTICATED', 'ENROLLMENT_STARTED', 'ENROLLMENT_COMPLETED', 'INTERVIEW_ACTIVE', 'INTERVIEW_PAUSED', 'INTERVIEW_COMPLETED', 'SUSPENDED', name='candidatestatus'), nullable=True))
    op.add_column('interviewsession', sa.Column('last_activity', sa.DateTime(), nullable=True))
    op.add_column('interviewsession', sa.Column('warning_count', sa.Integer(), nullable=False))
    op.add_column('interviewsession', sa.Column('max_warnings', sa.Integer(), nullable=False))
    op.add_column('interviewsession', sa.Column('is_suspended', sa.Boolean(), nullable=False))
    op.add_column('interviewsession', sa.Column('suspension_reason', sa.String(), nullable=True))
    op.add_column('interviewsession', sa.Column('suspended_at', sa.DateTime(), nullable=True))
    op.add_column('proctoringevent', sa.Column('severity', sa.String(), nullable=False))
    op.add_column('proctoringevent', sa.Column('triggered_warning', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proctoringevent', 'triggered_warning')
    op.drop_column('proctoringevent', 'severity')
    op.drop_column('interviewsession', 'suspended_at')
    op.drop_column('interviewsession', 'suspension_reason')
    op.drop_column('interviewsession', 'is_suspended')
    op.drop_column('interviewsession', 'max_warnings')
    op.drop_column('interviewsession', 'warning_count')
    op.drop_column('interviewsession', 'last_activity')
    op.drop_column('interviewsession', 'current_status')
    op.drop_table('statustimeline')
    # ### end Alembic commands ###
