"""remove_is_active_field_from_user

Revision ID: b118484d1c16
Revises: 6f4451f41118
Create Date: 2026-02-12 10:59:59.923187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b118484d1c16'
down_revision: Union[str, Sequence[str], None] = '6f4451f41118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
