"""add_team_and_interview_round

Revision ID: b8e64747425e
Revises: 50634a7115a4
Create Date: 2026-03-03 12:14:30.765881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b8e64747425e'
down_revision: Union[str, Sequence[str], None] = '50634a7115a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=True)
    op.add_column('interviewsession', sa.Column('team_id', sa.Integer(), nullable=True))
    # Create the PostgreSQL enum type before using it in the column
    interviewround_enum = sa.Enum('ROUND_1', 'ROUND_2', 'ROUND_3', 'ROUND_4', 'ROUND_5', name='interviewround')
    interviewround_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('interviewsession', sa.Column('interview_round', sa.Enum('ROUND_1', 'ROUND_2', 'ROUND_3', 'ROUND_4', 'ROUND_5', name='interviewround'), nullable=True))
    op.alter_column('interviewsession', 'allow_copy_paste',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_foreign_key(None, 'interviewsession', 'team', ['team_id'], ['id'], ondelete='SET NULL')
    op.add_column('questionpaper', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questionpaper', 'team', ['team_id'], ['id'], ondelete='SET NULL')
    # Clean up orphaned questions (paper_id IS NULL) before enforcing NOT NULL
    op.execute("DELETE FROM questions WHERE paper_id IS NULL")
    op.alter_column('questions', 'paper_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'paper_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'questionpaper', type_='foreignkey')
    op.drop_column('questionpaper', 'team_id')
    op.drop_constraint(None, 'interviewsession', type_='foreignkey')
    op.alter_column('interviewsession', 'allow_copy_paste',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('interviewsession', 'interview_round')
    op.drop_column('interviewsession', 'team_id')
    # Drop the enum type after the column using it is removed
    sa.Enum(name='interviewround').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###
