"""actually add invite_link

Revision ID: bb04cbdbc713
Revises: 5e1dbd0c8b43
Create Date: 2026-02-25 11:13:41.734861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb04cbdbc713'
down_revision: Union[str, Sequence[str], None] = '5e1dbd0c8b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviewsession', sa.Column('invite_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviewsession', 'invite_link')
    # ### end Alembic commands ###
