"""refactor_team_to_user

Revision ID: ce0f6c6b6e65
Revises: 47f7bcf4f97d
Create Date: 2026-03-10 14:13:27.552132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0f6c6b6e65'
down_revision: Union[str, Sequence[str], None] = '47f7bcf4f97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interviewresult', 'result_status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('interviewsession_team_id_fkey'), 'interviewsession', type_='foreignkey')
    op.drop_column('interviewsession', 'team_id')
    op.drop_constraint(op.f('questionpaper_team_id_fkey'), 'questionpaper', type_='foreignkey')
    op.drop_column('questionpaper', 'team_id')
    op.add_column('user', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'team', ['team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'team_id')
    op.add_column('questionpaper', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('questionpaper_team_id_fkey'), 'questionpaper', 'team', ['team_id'], ['id'], ondelete='SET NULL')
    op.add_column('interviewsession', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('interviewsession_team_id_fkey'), 'interviewsession', 'team', ['team_id'], ['id'], ondelete='SET NULL')
    op.alter_column('interviewresult', 'result_status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'PENDING'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
