"""add_interviewer_role

Revision ID: f1d4c0fd6b3f
Revises: 271e5c886c8d
Create Date: 2026-02-03 11:57:18.426352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1d4c0fd6b3f'
down_revision: Union[str, Sequence[str], None] = '271e5c886c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviewroom', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['interviewer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviewroom', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
