"""rename_adminUser_to_admin_user_snake_case

Revision ID: g1h2i3j4k5l6
Revises: d756d5580dba
Create Date: 2026-03-12 17:46:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'g1h2i3j4k5l6'
down_revision = 'd756d5580dba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Rename adminUser to admin_user in QuestionPaper table
    op.alter_column('questionpaper', 'adminUser',
                    existing_type=sa.INTEGER(),
                    existing_nullable=True,
                    new_column_name='admin_user')
    
    # Rename adminUser to admin_user in CodingQuestionPaper table
    op.alter_column('codingquestionpaper', 'adminUser',
                    existing_type=sa.INTEGER(),
                    existing_nullable=True,
                    new_column_name='admin_user')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Rename admin_user back to adminUser in QuestionPaper table
    op.alter_column('questionpaper', 'admin_user',
                    existing_type=sa.INTEGER(),
                    existing_nullable=True,
                    new_column_name='adminUser')
    
    # Rename admin_user back to adminUser in CodingQuestionPaper table
    op.alter_column('codingquestionpaper', 'admin_user',
                    existing_type=sa.INTEGER(),
                    existing_nullable=True,
                    new_column_name='adminUser')
    
    # ### end Alembic commands ###
